// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { monitor: string | null, active_theme: string | null, active_layout: string | null, preferences: Preferences, };

export type Core = { name: string, frequency: bigint, usage: number, };

export type CpuStats = { global_usage: number, processors: Array<Processor>, total_physical_cores: number, total_logical_cores: number, };

export type DiskInfo = { name: string, mount_point: string, file_system: string, kind: string, total_space: bigint, available_space: bigint, };

export type FrequencyReading = { freq_hi: number, freq_lo: number, magnitude: number, };

export type GridPadding = { top: number, right: number, bottom: number, left: number, };

export type GridSettings = { grid_rows: number, grid_cols: number, gap: number, padding: GridPadding, };

export type HardwareStats = { disks: Array<DiskInfo>, networks: Array<NetworkInterfaceInfo>, temperatures: Array<TemperatureReading>, };

export type LayoutFile = { id: string, name: string, widgets: Array<WidgetConfig>, grid_rows: number, grid_cols: number, gap: number, padding: GridPadding, };

/**
 * Lightweight summary returned by `list_layouts`.
 */
export type LayoutInfo = { id: string, name: string, };

export type MediaState = { 
/**
 * False when no media session is active; all other fields are empty/zero.
 */
active: boolean, playing: boolean, title: string, artist: string, album: string, 
/**
 * Base64-encoded thumbnail image (JPEG or PNG).
 */
album_art_b64: string | null, position_ms: bigint, duration_ms: bigint, };

export type MemoryStats = { used: bigint, total: bigint, swap_used: bigint, swap_total: bigint, };

export type NetworkInterfaceInfo = { name: string, received: bigint, transmitted: bigint, total_received: bigint, total_transmitted: bigint, mac_address: string, };

export type Preferences = { rounded: boolean, widget_transparent: boolean, background_transparent: boolean, font_scale: number, };

export type Processor = { brand: string, cores: Array<Core>, };

export type SystemStats = { cpu: CpuStats, memory: MemoryStats, };

export type TemperatureReading = { label: string, current: number, max: number, };

export type ThemeData = { id: string, name: string, vars: Array<ThemeVar>, color_scheme: string, };

/**
 * Lightweight summary returned by `list_themes`.
 */
export type ThemeInfo = { id: string, name: string, };

/**
 * A single typed CSS variable entry. The CSS variable name is assembled as
 * `--{type}-{label}` (e.g. Color { label: "base" } → `--color-base`).
 */
export type ThemeVar = { "type": "color", label: string, value: string, } | { "type": "font", label: string, value: Array<string>, };

export type WidgetConfig = { id: string, 
/**
 * The identifier of the widget type, e.g. "cpu", "memory", "custom-chart", etc.
 */
type: string, 
/**
 * The placement of the widget in the grid layout.
 */
placement: WidgetPlacement, 
/**
 * Arbitrary options for the widget, which can be used to configure its behavior and appearance.
 */
options?: Record<string, any>, };

export type WidgetId = string;

export type WidgetPlacement = { 
/**
 * 1-indexed CSS grid column start.
 */
col: number, 
/**
 * 1-indexed CSS grid row start.
 */
row: number, col_span: number, row_span: number, };
